Notes: 

- IRID011, IRID026 and IRID038 were excluded (no HTLV-1 clones detected)
- IRID039_S123 and SS04 (are the same)  confirmed
- IRID015 and SS14 (are the same) confirmed
- IRID062 and SS02 (are the same) confirmed
- IRID089 and SS20 (are the same) confirmed
- IRID015 and 032 are siblings

to check SS27, SS01, IRID2,3,5-10

IRID025_S236 was eliminated

```{r}

pacman::p_load(googlesheets4, tidyverse, DT,lubridate, gtsummary, gt, rmarkdown)

# ----------------------------
# - Step 0: Adquiring metadata from google and do replacements in the strings
htlv_metadata = read_sheet("https://docs.google.com/spreadsheets/d/14eZCI8lRsfIebXu-tpAxbuPEOhE6moAnTDKKKUQyNOI/edit?gid=0#gid=0") |>
  mutate(ID=stringr::str_replace(ID, "^PE_", "")) |>
  mutate(ID=stringr::str_replace(ID, "_S.*", ""))
#----------------------------------------
# - Step 1: Manipulation 
htlv_mdata = htlv_metadata |>
  filter(Complete!="NO_HTLV") |>
  select(
    ID, 
    Status, 
    Birth_place_DNI, 
    Sex, 
    Age, 
    "PVL1 (copies/10000PMBCs)", 
    strongy_lifetime, 
    disease_2) |>
  dplyr::rename(
    PVL_home="PVL1 (copies/10000PMBCs)",
    birthplace=Birth_place_DNI
  ) |>
  mutate(
    Status = case_when(
      Status == "vivo" ~ "Alive",
      Status == "death" ~ "Death",
      .default=NULL
    ),
    id_birth = case_when(  
      toupper(birthplace) %in% c("AMAZONAS", "LORETO", "MADRE_DE_DIOS", "SAN_MARTIN", "UCAYALI") ~ "Amazonian region",
      toupper(birthplace)  %in% c("ANCASH", "AREQUIPA", "CALLAO", "ICA", "LA_LIBERTAD",   "LAMBAYEQUE", "LIMA", "MOQUEGUA", "PIURA", "TACNA", "TUMBES") ~ "Coastal region",
      toupper(birthplace) %in% c("PUNO", "HUANCAVELICA", "HUANUCO", "APURIMAC", "AYACUCHO", "CAJAMARCA", "JUNIN", "PASCO",  "CUSCO") ~ "Andean region"),
      Age=as.numeric(Age),
      Sex=recode(Sex, F = "Female", M = "Male"),
      disease_2=recode(disease_2, AC="Asymptomatic carriers", ATL="ATLL", HAM="HAM/TSP"),
      strongy_lifetime=recode(strongy_lifetime, YES="Strongyloides (+)",
      NO="Strongyloides (-)")

  )

# Preliminary review
datatable(htlv_mdata)
#---------------------------------------
# Table 1 - Final - gtsummary
table1 = htlv_mdata |>
  select(strongy_lifetime, -ID, -birthplace, -PVL_home, Sex, Age, id_birth, disease_2, Status, ) |>
  gtsummary::tbl_summary(
    by="strongy_lifetime",
    missing="no",
    type= list(
      Sex ~ "categorical",
      Age ~ "continuous",
      id_birth ~ "categorical",
      disease_2 ~ "categorical",
      Status ~ "categorical"),
    label=list(
      Sex ~ "Sex",
      Age ~ "Age(years)",
      id_birth ~ "Birthplace",
      disease_2 ~ "Disease outcome",
      Status ~ "5-year mortality rate"),
    ) |>
  gtsummary::add_overall(last=FALSE, col_label="**Total**") |>
  gtsummary::add_p() |>
  modify_header(label="**Variable**", all_stat_cols() ~ "**{level}**<br>N = {n} ({style_percent(p, digits=1)}%)") |>
  bold_labels() %>%
  as_gt()
table1
gtsave(table1, filename = "2503_Table1.docx", path="./output")
```

```{r}
pacman::p_load(tidyverse, ineq, tidyplots,DT)

#------------------
# Gini's index formula based on tags
gini_index <- function(counts) {
  n <- length(counts)
  mean_count <- mean(counts)
  sum_abs_diff <- sum(sapply(counts, function(x) sum(abs(x - counts))))
  gini <- sum_abs_diff / (2 * n^2 * mean_count)
  return(gini)
}

# Step 1 - Loading clonality total file
htlv_is = read_tsv("concatenated_clonality.txt", col_names = c("range", "chrom", "start", "end", "freq", "freq_p", "sample"))

# Option A for gini index
result <- htlv_is |>
  group_by(sample) |>
  summarise(gini = Gini(freq), .groups = 'drop') |>
  filter(gini0.4) # filtering those with high oligoclonality

# Option B - Official, using ineq and join
result <- htlv_is |>
group_by(sample) |>
group_split() |>
map_dfr(~tibble(
  sample = .x$sample[1], 
  gini = Gini(.x$freq),
  sum_freq = sum(.x$freq)
  )) |>
  mutate(
    sample=stringr::str_replace(sample, "^Peru_", "")) 

datatable(result)

# 1-----Plotting OCI vs Abundance (pearson)
result |>
    dplyr::right_join(htlv_mdata, by=c("sample"="ID")) |>
tidyplot(x=gini, y=sum_freq, color=disease_2) |>
add_data_points(alpha=0.95) |>
adjust_x_axis(title = "Oligoclonality Index (OCI)", limits=c(0,1.1)) |>
adjust_y_axis(title = "Integration Sites (IS) \nNGS Abundance", limits=c(0,800)) |>
adjust_legend_title("Disease") |>
adjust_colors(new_colors = c("#3B78B0", "#E64B35B2","#7E6148B2")) |>
add_annotation_text(paste0("r = ", corr), x=0.25, y=700, fontsize = 7) |>
save_plot("output/oci.png", 
  view_plot = TRUE,
  bg = "transparent",
  width = 10,
  height = 7, 
  unit="cm")

corr=round(cor(result$gini, result$sum_freq, method = c("pearson")), 4)

datatable(result)
# 2-----Plotting OCI vs Strongy
result |>
 dplyr::right_join(htlv_mdata, by=c("sample"="ID")) |>
tidyplot(x=strongy_lifetime, y=gini) |>
add_data_points_jitter(alpha=0.95) |>
add_violin(draw_quantiles = 0.5, alpha=0.2) |>
add_test_pvalue(method="t_test", method.args = list(alternative = "two.sided", var.equal = FALSE), hide_info = TRUE) |>
adjust_y_axis(title = "Oligoclonality Index (OCI)", limits=c(-0.1,1.1)) |>
adjust_x_axis(title = NULL) |>
save_plot("output/S1_Strongi_vs_OCI.png", 
  view_plot = TRUE,
  bg = "transparent",
  width = 7,
  height = 8, 
  unit="cm") 

# 3-----Plotting OCI vs NGS reads
result |>
 dplyr::right_join(htlv_mdata, by=c("sample"="ID")) |>
tidyplot(x=strongy_lifetime, y=sum_freq) |>
add_data_points_jitter(alpha=0.95) |>
add_violin(draw_quantiles = 0.5, alpha=0.2) |>
add_test_pvalue(method="t_test", method.args = list(alternative = "two.sided", var.equal = FALSE), hide_info = TRUE) |>
adjust_y_axis(title = "Integration Sites (IS) \nNGS Abundance") |>
adjust_x_axis(title = NULL) |>
save_plot("output/S1_Strongi_vs_NGSreads.png", 
  view_plot = TRUE,
  bg = "transparent",
  width = 7,
  height = 8, 
  unit="cm")
```

