---
title: "Supplementary_Figure1"
output: html_notebook
---

```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
getwd()
estructura<-c("data", "scriptsRmd", "output", "output_knit")
for (name in estructura){
  path<-paste0(getwd(),"/",name)
  dir.create(path, recursive = TRUE)}
pacman::p_load(Gmisc,grid,svglite)
```

Supplementary Figure S1 – Flowchart of sequences kept during the filtering process.
```{r echo=FALSE}
#basic position parameters
leftxa<-.15
leftxb<-.4
midx<-.5
rightxa<-.6
rightxb<-.85
rightxbf<-.8


#Define features of main boxes (NCBI and htlv)
mainbox<-gpar(fill="#226e9c", col="#3c93c2")
maintxt<-gpar(col="white", cex=1,fontface="bold")

mainbox2<-gpar(fill="#f28522", col="#FABF7B")
maintxt2<-gpar(col="white", cex=1,fontface="bold")

mainbox3<-gpar(fill="#089099", col="#46AEA0")
maintxt3<-gpar(col="white", cex=1,fontface="bold")

#Define features of description boxes (NCBI and htlv, mainpath)
dbox<-gpar(fill="#E4F1F7",col="#E4F1F7")
dtxt<-gpar(col="black", cex=0.8)

dbox2<-gpar(fill="#FCE1A4",col="#FCE1A4")
dtxt2<-gpar(col="black", cex=0.8)

dbox3<-gpar(fill="#E1F2E3",col="#E1F2E3")
dtxt3<-gpar(col="black", cex=0.8)

#connectors
gp1=getOption("ConnectGrob", default=gpar(col="#A0B1BA", fill="#A0B1BA", lex=2))
arrow1=getOption("connectGrobArrow", default=arrow(type="closed", length = unit(0.01,"npc")))
```

```{R}
#new page
png("../output/2405tree/supplement_Fig1.png", width=3000, height=2500, res=300)
#svglite(filename = "Sup1.svg",width=10, height = 8)
grid.newpage()
#create main boxes NCBI

box1<-boxGrob("BLAST search \n(n=444)",
              just="center",
              y=0.85,
              x=leftxb,
              box_gp=mainbox,
              txt_gp=maintxt)

box2<-boxGrob("Eligibility criteria\n(n=327)",
              just="center",
              y=0.70,
              x=leftxb,
              box_gp=mainbox,
              txt_gp=maintxt)

box3<-boxGrob("Genbank human\nsequences (n=320)",
              just="center",
              y=0.55,
              x=leftxb,
              box_gp=mainbox,
              txt_gp=maintxt)

#conectors
connectGrob(box1,box2,type="N", lty_gp=gp1, arrow_obj=arrow1)
connectGrob(box2,box3,type="N", lty_gp=gp1, arrow_obj=arrow1)


#create description boxes NCBI

box5<-boxGrob("BLAST nucleotide search\n- Query sequence = J02029.1\n- Length filter = 6000-10000bp\n- Date = November 2023",
              just="left",
              y=.85,
              x=leftxa,
              box_gp=dbox,
              txt_gp=dtxt)

box6<-boxGrob("Identity >60% and filtered\nby Taxonomy ID: 11908", 
              just="left",
              y=.70,
              x=leftxa,
              box_gp=dbox,
              txt_gp=dtxt)

box7<-boxGrob("Cell lines sequences excluded:\n- Human (n=4):\nM86840, LC378575, D13784,\nAB979451.\n- Animal (n=3):\nL03562, L03561, KU214243.1",
              just="left",
              y=.55,
              x=leftxa,
              box_gp=dbox,
              txt_gp=dtxt)

#create main boxes htlv

box8<-boxGrob("Primary Samples\n(n=71)",
              just="center",
              y=0.85,
              x=rightxa,
              box_gp=mainbox2,
              txt_gp=maintxt2)

box9<-boxGrob("Eligibility criteria\n(n=67)",
              just="center",
              y=0.70,
              x=rightxa,
              box_gp=mainbox2,
              txt_gp=maintxt2)

box10<-boxGrob("Unique sequences\n(n=63)",
              just="center",
              y=0.55,
              x=rightxa,
              box_gp=mainbox2,
              txt_gp=maintxt2)

#conectors
connectGrob(box8,box9,type="N", lty_gp=gp1, arrow_obj=arrow1)
connectGrob(box9,box10,type="N", lty_gp=gp1, arrow_obj=arrow1)


#create description boxes htlv
hd1<-boxGrob("Consensus HTLV-1 sequences:\n- 71 CG samples (Peru)",
              just="left",
              y=.85,
              x=rightxb,
              box_gp=dbox2,
              txt_gp=dtxt2)

hd2<-boxGrob("Filtered by: lenght >6000 bp \nand >5x coverage.\n- Excluded:\nIRID011_S130, IRID038_S122,\nIRID040_S124, IRID067_S233", 
              just="left",
              y=.70,
              x=rightxb,
              box_gp=dbox2,
              txt_gp=dtxt2)

hd3<-boxGrob("Time series sequences excluded:\n \nIRID026_S237, PE_SS02_S1, \nPE_SS04_S3, PE_SS20_S204",
              just="left",
              y=.55,
              x=rightxb,
              box_gp=dbox2,
              txt_gp=dtxt2)

#main path

box4<-boxGrob("HTLV-1 nucleotide dataset\n(n=383)",
              just="center",
              y=0.40,
              x=midx,
              box_gp=mainbox3,
              txt_gp=maintxt3)

box11<-boxGrob("Aligned dataset\n(n=380)",
              just="center",
              y=0.25,
              x=midx,
              box_gp=mainbox3,
              txt_gp=maintxt3)

box12<-boxGrob("Final nucleotide HTLV-1 dataset\n(n=380)",
              just="center",
              y=0.1,
              x=midx,
              box_gp=mainbox3,
              txt_gp=maintxt3)
#conectors
connectGrob(box10,box4,type="v", "r", lty_gp=gp1, arrow_obj=arrow1)
connectGrob(box4,box11,type="N", lty_gp=gp1, arrow_obj=arrow1)
connectGrob(box11,box12,type="N", lty_gp=gp1, arrow_obj=arrow1)
connectGrob(box3,box4,type="v","l", lty_gp=gp1, arrow_obj=arrow1)

#main path description
maind1<-boxGrob("Sequences with potential\nrecombination signal were excluded:\nKF797883, KY007245, KY007246",
              just="left",
              y=.40,
              x=rightxbf,
              box_gp=dbox3,
              txt_gp=dtxt3)

maind2<-boxGrob("MAFFT Global Alignment, VIRULIGN  \n*Dataset for cluster and Bayesian \nanalyses (n=373)", 
              just="left",
              y=.25,
              x=rightxbf,
              box_gp=dbox3,
              txt_gp=dtxt3)


firstline<-alignVertical(reference=box1, box1, box5, box8, hd1, .position="top")
a_main<-alignHorizontal(reference=box1, box2, box3, .position="center")
a2_main<-alignHorizontal(reference=box8, box9,box10,.position = "center")
a3_main<-alignHorizontal(reference=box4, box4, box11, box12, .position="center")
a_des<-alignHorizontal(reference=box5, box6, box7, .position = "left")
h_des<-alignHorizontal(reference=hd1, hd2,hd3, .position="right")
m_des<-alignHorizontal(reference=maind1, maind1, maind2, .position="left")

firstline
a_main
a2_main
a3_main
a_des
h_des
m_des

#close the file
dev.off()

```

