Notes: 

- IRID011, IRID026 and IRID038 were excluded (no HTLV-1 clones detected)
- IRID039_S123 and SS04 (are the same)  confirmed
- IRID015 and SS14 (are the same) confirmed
- IRID062 and SS02 (are the same) confirmed
- IRID089 and SS20 (are the same) confirmed
- IRID015 and 032 are siblings

to check SS27, SS01, IRID2,3,5-10

IRID025_S236 was eliminated

```{r}
## Loading Packages
pacman::p_load(googlesheets4, tidyverse, DT,lubridate, gtsummary, gt, rmarkdown)
#----------------------------
## Loading Packages
# - Step 0: Adquiring metadata from google and do replacements in the strings
htlv_metadata = read_sheet("https://docs.google.com/spreadsheets/d/14eZCI8lRsfIebXu-tpAxbuPEOhE6moAnTDKKKUQyNOI/edit?gid=1412798579#gid=1412798579", sheet="Sheet3") |>
  mutate(ID=stringr::str_replace(ID, "^PE_", "")) |>
  mutate(ID=stringr::str_replace(ID, "_S.*", ""))
#----------------------------
# - Step 1: Manipulation 
#htlv_mdata = htlv_metadata |>
  #filter(Complete!="NO_HTLV") |>

htlv_mdata  = htlv_metadata |>
  dplyr::select(
    ID, 
    Status, 
    Birth_place_DNI, 
    Sex, 
    Age, 
    PVL2, 
    gini,
    strongy_lifetime, 
    disease_2,
    ) |>
  dplyr::rename(
    birthplace=Birth_place_DNI
  ) |>
  mutate(
    Status = case_when(
      Status == "vivo" ~ "Alive",
      Status == "death" ~ "Death",
      .default=NULL
    ),
    id_birth = case_when(  
      toupper(birthplace) %in% c("AMAZONAS", "LORETO", "MADRE_DE_DIOS", "SAN_MARTIN", "UCAYALI") ~ "Amazonian region",
      toupper(birthplace)  %in% c("ANCASH", "AREQUIPA", "CALLAO", "ICA", "LA_LIBERTAD",   "LAMBAYEQUE", "LIMA", "MOQUEGUA", "PIURA", "TACNA", "TUMBES") ~ "Coastal region",
      toupper(birthplace) %in% c("PUNO", "HUANCAVELICA", "HUANUCO", "APURIMAC", "AYACUCHO", "CAJAMARCA", "JUNIN", "PASCO",  "CUSCO") ~ "Andean region"),
      Age=as.numeric(Age),
      Sex=recode(Sex, F = "Female", M = "Male"),
      disease_2=recode(disease_2, AC="Asymptomatic carriers", ATL="ATLL", HAM="HAM/TSP"),
      strongy_lifetime=recode(strongy_lifetime, YES="Strongyloides (+)",
      NO="Strongyloides (-)")

  )
# Preliminary review
DT::datatable(htlv_mdata)
#---------------------------------------
## Table 1 - Final - gtsummary
table1 = htlv_mdata |>
  dplyr::mutate(PVLc=ifelse(PVL2>=4, "High-Risk", "Low-Risk")) |>
  dplyr::select(strongy_lifetime, -ID, -birthplace, Sex, Age, id_birth,  PVL2, PVLc, gini, disease_2,Status) |>
  gtsummary::tbl_summary(
    by="strongy_lifetime",
    missing="no",
    type= list(
      Sex ~ "categorical",
      Age ~ "continuous",
      id_birth ~ "categorical",
      disease_2 ~ "categorical",
      Status ~ "categorical",
      PVL2 ~ "continuous",
      PVLc ~ "categorical",
      gini ~ "continuous"),
    label=list(
      Sex ~ "Sex",
      Age ~ "Age(years)",
      id_birth ~ "Birthplace",
      PVL2 ~ "Proviral Load (PVL,%)",
      PVLc ~ "PVL-Risk (≥4%)",
      gini ~ "OCI",
      disease_2 ~ "7-year Disease outcome",
      Status ~ "7-year Vital status"),
    statistic = list(
      # Ensure proper statistics for categorical variables
      PVLc ~ "{n} ({p})",
      all_categorical() ~ "{n} ({p})",
      all_continuous() ~ "{median} ({p25}, {p75})"
    ),
      digits = list(
      Age ~ 1,
      PVL2 ~ 1,
      gini ~1
    )
    ) |>
  gtsummary::add_p() |>
  gtsummary::modify_header(label="**Variable**", all_stat_cols() ~ "**{level}**<br>N = {n} ({style_percent(p, digits=1)}%)") |>
  gtsummary::bold_labels() |>
  gtsummary::add_overall(last=TRUE, col_label="**Total**") |>
  as_gt()
library(gtsummary)
table1
gtsave(table1, filename = "2508_Table1.docx", path="./output")
#---------------------------------------
## Predictors of PVL - PVL DOES NOT FOLLOW A NORMAL DISTRIBUTION
htlv_mdata |>
dplyr::mutate(PVLc=ifelse(PVL2>=4, "High-Risk", "Low-Risk")) |>
janitor::tabyl(PVLc, strongy_lifetime ) |>
janitor::adorn_percentages("col") |>
  janitor::adorn_pct_formatting(digits = 1) |>
  janitor::adorn_ns() 

hist(htlv_mdata$PVL2, breaks = 20, main = "Histogram of PVL", xlab = "PVL (%)")
qqnorm(htlv_mdata$PVL2); qqline(htlv_mdata$PVL)
shapiro.test(htlv_mdata$PVL2) # If n < 5000
# Not follow a normal distribution
htlv_mdata$PVLd = log(htlv_mdata$PVL2)
shapiro.test(htlv_mdata$PVLd) # If n < 5000

#---------------------------------------
## Predictors of PVL
pacman::p_load(betareg, MASS)
robust_model <- rlm(PVL2 ~ Age + Sex + strongy_lifetime + id_birth, data = htlv_mdata) 
r1 =robust_model |>
tbl_regression()
r1 |>
as_gt() #|>
gtsave(filename = "2508_sup_PVLregresionA.docx", path="./output")

summary(robust_model)

htlv_mdata$PVLc = (htlv_mdata$PVL2/100)
beta_model <- betareg::betareg(PVLc ~ Age + Sex + strongy_lifetime + id_birth, data = htlv_mdata)
r2 = beta_model |>
  tbl_regression()
summary(beta_model)
tbl_merge(list(r1, r2)) |>
  as_gt() |>
  gtsave(filename = "2508_sup_PVLregresion.docx", path="./output")

#---------------------------------------
## Predictors of Death
htlv_mdata = htlv_mdata |>
  dplyr::mutate(status2=ifelse(is.na(Status), "Death", Status))
unique(htlv_mdata$status2)
n_deaths <- sum(htlv_mdata$Status == "Death", na.rm = TRUE)
n_total <- nrow(htlv_mdata)
risk <- n_deaths / n_total
ci <- binom.test(n_deaths, n_total)$conf.int
cat(sprintf("Cumulative mortality risk: %.1f%% (95%% CI: %.1f%%–%.1f%%)", risk*100, ci[1]*100, ci[2]*100))

# Logistic regression model
htlv_mdata
htlv_mdata$status1 = ifelse(htlv_mdata$Status=="Death", 1, 0)
logit_model <- glm(status1  ~ Age + Sex + PVL2 + strongy_lifetime, 
                   data = htlv_mdata, 
                   family = binomial)
summary(logit_model)
exp(cbind(OR = coef(logit_model), confint(logit_model)))

logit_model |>
  tbl_regression(exponentiate = TRUE) |>
  as_gt() |>
  gtsave(filename = "2508_sup_deathregresion.docx", path="./output")

# Including lost
htlv_mdata$status2 = ifelse(htlv_mdata$Status=="death", 1, 0)
logit_model2 <- glm(status2  ~ Age + Sex + strongy_lifetime + PVL, 
                   data = htlv_mdata, 
                   family = binomial)
summary(logit_model)
logit_model2 |>
  tbl_regression(exponentiate = TRUE)
exp(cbind(OR = coef(logit_model), confint(logit_model)))

```

```{r}
pacman::p_load(tidyverse, ineq, tidyplots, DT)

#------------------
# Gini's index formula based on tags
gini_index <- function(counts) {
    n <- length(counts)
    mean_count <- mean(counts)
    sum_abs_diff <- sum(sapply(counts, function(x) sum(abs(x - counts))))
    gini <- sum_abs_diff / (2 * n^2 * mean_count)
    return(gini)
}

# Step 1 - Loading clonality total file
htlv_is <- read_tsv("./250212_clonality_table1/concatenated_clonality.txt", col_names = c("range", "chrom", "start", "end", "freq", "freq_p", "sample"))

# Option A for gini index
result <- htlv_is |>
    group_by(sample) |>
    summarise(gini = Gini(freq), .groups = "drop") #|>
    filter(gini0.4) # filtering those with high oligoclonality

result = result |>
  mutate(sample=stringr::str_remove(sample, "^Peru_"))
datatable(result)
### Adding clonality to the datasets
db_update = googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/14eZCI8lRsfIebXu-tpAxbuPEOhE6moAnTDKKKUQyNOI/edit?gid=1412798579#gid=1412798579", sheet="Sheet3")

db_update = db_update |>
  left_join(result, by=c("ID2"="sample"))
### Updating dataset
googlesheets4::write_sheet(db_update, "https://docs.google.com/spreadsheets/d/14eZCI8lRsfIebXu-tpAxbuPEOhE6moAnTDKKKUQyNOI/edit?gid=1412798579#gid=1412798579", sheet="Sheet3")

# Option B - Official, using ineq and join
result <- htlv_is |>
    group_by(sample) |>
    group_split() |>
    map_dfr(~ tibble(
        sample = .x$sample[1],
        gini = Gini(.x$freq),
        sum_freq = sum(.x$freq)
    )) |>
    mutate(
        sample = stringr::str_replace(sample, "^Peru_", "")
    )
summary_stats <- result %>%
    dplyr::summarise(
        mean_gini = mean(gini, na.rm = TRUE), # Mean of gini
        sd_gini = sd(gini, na.rm = TRUE), # Standard deviation of gini
        n = n(), # Sample size
        se = sd_gini / sqrt(n), # Standard error
        ci_lower = mean_gini - qt(0.975, df = n - 1) * se, # Lower bound of 95% CI
        ci_upper = mean_gini + qt(0.975, df = n - 1) * se # Upper bound of 95% CI
    )
summary_stats

datatable(htlv_mdata)
htlv_mdata
gin_df <- htlv_mdata |>
    left_join(result, by = c("ID" = "sample"))


htlv_mdata |>
    left_join(result, by = c("ID" = "sample")) |>
    group_by(disease_2) |>
    dplyr::summarise(
        mean_gini = mean(gini, na.rm = TRUE), # Mean of gini
        sd_gini = sd(gini, na.rm = TRUE), # Standard deviation of gini
        n = n(), # Sample size
        se = sd_gini / sqrt(n), # Standard error
        ci_lower = mean_gini - qt(0.975, df = n - 1) * se, # Lower bound of 95% CI
        ci_upper = mean_gini + qt(0.975, df = n - 1) * se # Upper bound of 95% CI
    )


### welch test between gini and disease
db_update = googlesheets4::read_sheet( "https://docs.google.com/spreadsheets/d/14eZCI8lRsfIebXu-tpAxbuPEOhE6moAnTDKKKUQyNOI/edit?gid=1412798579#gid=1412798579", sheet="Sheet3")

labelx = paste("Spearman rho =", 
                          round(cor(db_update$PVL, db_update$gini, 
                                    method="spearman", use="complete.obs"), 2),
                          "\np =", round(cor.test(db_update$PVL, db_update$gini, 
                                        method="spearman")$p.value, 7))
labelx
cor.test(htlv_db$meanCOV, htlv_db$PVL, 
                                        method="spearman")

db_update |>
    tidyplots::tidyplot(x=gini, y=PVL, color=disease_2) |>
    tidyplots::add_data_points_beeswarm(size=1.5, preserve="total", alpha=.8) |>
    tidyplots::add(geom_smooth(
      method = "lm", 
      se = FALSE, 
      color = "black", 
      size=.5,
      inherit.aes=FALSE, aes(x=gini, y=PVL),
      alpha = 0.4
      )) |>
    tidyplots::add_annotation_text(
      labelx,
      x = min(db_update$gini, na.rm=TRUE) + 0.3,
      y = max(db_update$PVL, na.rm=TRUE) - 1,
    ) |>
     tidyplots::adjust_x_axis_title("Oligoclonality Index (OCI)", face="bold") |>
    tidyplots::adjust_y_axis_title("Proviral Load (% PBMC)", face="bold") |>
    tidyplots::adjust_legend_title("Last Disease \nStatus") |>
    tidyplots::adjust_colors(new_colors=c("#377EB8", "#E41A1C", "#a6611a")) |>
    tidyplots::adjust_font(face="bold") |>
    tidyplots::save_plot("output/2508_PVL_vsGini.png", bg="transparent")

welch_test <- db_update |>
    oneway.test(gini ~ strongy_lifetime, data = _, var.equal = FALSE) # Welch's t-test

# Print Welch's t-test results
print(welch_test)
unique(db_update$disease_2)
db_update |>
    tidyplots::tidyplot(x = disease_2, y = gini, color = disease_2) |>
    tidyplots::add_data_points_jitter() |>
    tidyplots::add_boxplot() |>
    tidyplots::add_test_pvalue() |>
    tidyplots::remove_legend() |>
    tidyplots::remove_caption() |>
    tidyplots::adjust_y_axis_title("Oligoclonality Index (OCI)") |>
    tidyplots::remove_x_axis_title() |>
    tidyplots::sort_x_axis_labels() |>
    tidyplots::adjust_font(face = "bold") |>
    tidyplots::save_plot("output/2505_ociby_disease.png",
        view_plot = TRUE,
        bg = "transparent",
        width = 10,
        height = 10,
        unit = "cm"
    )


datatable(gin_df)
# 1-----Plotting OCI vs Abundance (pearson)
result |>
    dplyr::right_join(htlv_mdata, by = c("sample" = "ID")) |>
    tidyplot(x = gini, y = sum_freq, color = disease_2) |>
    add_data_points(alpha = 0.95) |>
    adjust_x_axis(title = "Oligoclonality Index (OCI)", limits = c(0, 1.1)) |>
    adjust_y_axis(title = "Integration Sites (IS) \nNGS Abundance", limits = c(0, 800)) |>
    adjust_legend_title("Disease") |>
    adjust_colors(new_colors = c("#3B78B0", "#E64B35B2", "#7E6148B2")) |>
    add_annotation_text(paste0("r = ", corr), x = 0.25, y = 700, fontsize = 7) |>
    save_plot("output/oci.png",
        view_plot = TRUE,
        bg = "transparent",
        width = 10,
        height = 7,
        unit = "cm"
    )

corr <- round(cor(result$gini, result$sum_freq, method = c("pearson")), 4)

datatable(result)
# 2-----Plotting OCI vs Strongy
db_update |>
    tidyplots::tidyplot(x = strongy_lifetime, y = gini) |>
    tidyplots::add_data_points_jitter(alpha = 0.95) |>
    tidyplots::add_violin(draw_quantiles = 0.5, alpha = 0.2) |>
    tidyplots::add_test_pvalue(method = "t_test",  hide_info = TRUE) |>
    tidyplots::adjust_y_axis(title = "Oligoclonality Index (OCI)", limits = c(-0.1, 1.1)) |>
    tidyplots::adjust_x_axis(title = NULL, labels=c("No-LSI","LSI")) |>
    tidyplots::save_plot("output/2508_S1_Strongi_vs_OCI.png",
        view_plot = TRUE,
        bg = "transparent",
        width = 7,
        height = 8,
        unit = "cm"
    )

# 3-----Plotting OCI vs NGS reads
result |>
    dplyr::right_join(htlv_mdata, by = c("sample" = "ID")) |>
    tidyplot(x = strongy_lifetime, y = sum_freq) |>
    add_data_points_jitter(alpha = 0.95) |>
    add_violin(draw_quantiles = 0.5, alpha = 0.2) |>
    add_test_pvalue(method = "t_test", method.args = list(alternative = "two.sided", var.equal = FALSE), hide_info = TRUE) |>
    adjust_y_axis(title = "Integration Sites (IS) \nNGS Abundance") |>
    adjust_x_axis(title = NULL) |>
    save_plot("output/S1_Strongi_vs_NGSreads.png",
        view_plot = TRUE,
        bg = "transparent",
        width = 7,
        height = 8,
        unit = "cm"
    )
```

