---
format:docx
---

## Model Comparison: Whole-Genome vs. Partitioned Approaches

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+
| Analysis Approach                                                                                                                                                          | Best Fit Model                                                                                                                                                             | Log-likelihood of consensus tree | AIC        | AICc       | BIC           |
+:===========================================================================================================================================================================+:==========================================================================================================================================================================:+:================================:+:==========:+:==========:+==============:+
| **Whole-genome (unpartitioned)**                                                                                                                                           | TN+F+I+G4                                                                                                                                                                  | -52,081.35                       | 105,770.69 | 105,928.01 | 111,486.04    |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+
| **Partition 1: 5LTR + 3LTR, Partition 2: Core genes, Partition 3: Auxiliary genes**                                                                                        | Partition 1: TIM2+F+R3;                                                                                                                                                    | -26,457.10                       | 54,546.19  | 54,866.86  | **59,860.13** |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
|                                                                                                                                                                            | Partition 2: TN+F+I+R2;                                                                                                                                                    |                                  |            |            |               |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
|                                                                                                                                                                            | Partition 3: GTR+F+G4                                                                                                                                                      |                                  |            |            |               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+
| Analysis Approach                                                                                                                                                          | Best Fit Model                                                                                                                                                             | Log-likelihood                   | AIC        | AICc       | BIC           |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+
| **Whole-genome (unpartitioned)**                                                                                                                                           | TN+F+I+G4                                                                                                                                                                  | -52,081.35                       | 10,5770.69 | 10,5928.01 | 111,486.04    |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+
| **2 Partitions:\                                                                                                                                                           | P1: TIM2+F+I+G4 , P2: TN+F+I+G4                                                                                                                                            | -46,055.17                       | 93736.33   | 93919.12   | 99422.49      |
| P1: 5LTR + 3LTR**                                                                                                                                                          |                                                                                                                                                                            |                                  |            |            |               |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| **P2: env (3rd nucleotide) and rest of HTLV-1 genome**                                                                                                                     |                                                                                                                                                                            |                                  |            |            |               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+
| Only env                                                                                                                                                                   |                                                                                                                                                                            |                                  |            |            |               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+
| LTR and env (2-partition model)                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+
| All Partitions:                                                                                                                                                            | P1: TIM2+F+G4;                                                                                                                                                             | -26462.39                        | 54584.79   | 54,917.67  | 59,989.90     |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| P1: 5LTR_3LTR,                                                                                                                                                             | P2: HKY+F+G4;                                                                                                                                                              |                                  |            |            |               |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| P2: gag_p19_env_gp21_px_p30_px_p27,                                                                                                                                        | P3: K2P+I;                                                                                                                                                                 |                                  |            |            |               |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| P3: gag_p24_px_27,                                                                                                                                                         | P4: TIM2+F+I+G4;                                                                                                                                                           |                                  |            |            |               |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| P4: gag_p15_pro_p14_env_gp46_px_p13,                                                                                                                                       | P5: TN+F+I+G4;                                                                                                                                                             |                                  |            |            |               |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| P5: pol_p95_px_tax,                                                                                                                                                        | P6: GTR+F+G4                                                                                                                                                               |                                  |            |            |               |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| P6: px_p12_px_p8_HBZ_HBZ_SI                                                                                                                                                |                                                                                                                                                                            |                                  |            |            |               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+
| TN+F+R3: 5LTR_3LTR_pro_p14, TN+F+I+R2: gag_p19_gag_p15_env_gp46_env_gp21_px_p30_px_p13_px_p27, TN+F+I+R2: gag_p24_pol_p95_px_27_px_tax, GTR+F+G4: px_p12_px_p8_HBZ_HBZ_SI; | TN+F+R3: 5LTR_3LTR_pro_p14, TN+F+I+R2: gag_p19_gag_p15_env_gp46_env_gp21_px_p30_px_p13_px_p27, TN+F+I+R2: gag_p24_pol_p95_px_27_px_tax, GTR+F+G4: px_p12_px_p8_HBZ_HBZ_SI; | -26,388.89                       | 54425.77   | 54753.38   | 59791.80      |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+
| **Partition 1: 5LTR + 3LTR, Partition 2: Core genes, Partition 3: Auxiliary genes**                                                                                        | Partition 1: TIM2+F+R3;                                                                                                                                                    | -26,457.10                       | 54,546.19  | 54,866.86  | **59,860.13** |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
|                                                                                                                                                                            | Partition 2: TN+F+I+R2;                                                                                                                                                    |                                  |            |            |               |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
|                                                                                                                                                                            | Partition 3: GTR+F+G4                                                                                                                                                      |                                  |            |            |               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+
| All regions included                                                                                                                                                       | Partition 1: TIM2+F+I+R3                                                                                                                                                   | -92686.00                        | 186,994.00 | 187,076.31 | 193,262.95    |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| Partition 1: LTR region, rest of genome, nucleotide position 2.                                                                                                            | Partition 2: TN+F+I+R3                                                                                                                                                     |                                  |            |            |               |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| Partition 2:gag, pol-pro, env, pX, nucleotide position 1                                                                                                                   | Partition 3: TN+F+R3                                                                                                                                                       |                                  |            |            |               |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| Partition 3: nucleotide position 3                                                                                                                                         |                                                                                                                                                                            |                                  |            |            |               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+
| All regions included (and all genes with nucleotide position 1, 2, and 3)                                                                                                  | Partition 1: TIM2+F+I+R3                                                                                                                                                   | -92,986.88                       | 187,593.62 | 187,676.77 | 193,893.50    |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| Partition 1: LTR region, rest of genome, nucleotide position 2.                                                                                                            | Partition 2: TN+F+I+R3                                                                                                                                                     |                                  |            |            |               |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| Partition 2:gag, pol-pro, env, pX, nucleotide position 1                                                                                                                   | Partition 3: TIM2+F+I+R4                                                                                                                                                   |                                  |            |            |               |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| Partition 3: nucleotide position 3                                                                                                                                         |                                                                                                                                                                            |                                  |            |            |               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+
| Whole HTLV-1 genome and env (nucleotide position 3)                                                                                                                        | Partition 1: TIM2+F+I+R3                                                                                                                                                   | -54986.65                        | 111,575.30 | 111,718.55 | 117,332.23    |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| Partition 1: LTR region, rest of genome                                                                                                                                    | Partition 2: TN+F+I+R3                                                                                                                                                     |                                  |            |            |               |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| Partition 2: gag, pol-pro, env, pX, env (nucleotide position 3)                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+
| Whole HTLV-1 genome and env (nucleotide position 1, 2, and 3)                                                                                                              | Partition 1: TIM2+F+I+R3                                                                                                                                                   | -52667.42                        | 106,936.83 | 107,088.38 | 112,652.46    |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| Partition 1: LTR region, rest of genome, env (nucleotide position 2)                                                                                                       | Partition 2: TN+F+I+R3                                                                                                                                                     |                                  |            |            |               |
|                                                                                                                                                                            |                                                                                                                                                                            |                                  |            |            |               |
| Partition 2: gag, pol-pro, env, pX, env (nucleotide position 1 and 3)                                                                                                      |                                                                                                                                                                            |                                  |            |            |               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------+------------+------------+---------------+

Analyses was performed with IQ-TREE multicore version 2.3.5 for MacOS ARM 64-bit, using the module TESTMERGE on all complete HTLV-1 genomes (NCBI and Peruvian Sequences). AIC: Akaike information criterion scores; AICc: Corrected AIC scores. BIC: Bayesian information criterion scores; and Log-likelihood: Tree log-likelihood. The three-partition model was selected as the best fit due to its significantly lower BIC score and superior log-likelihood compared to the whole-genome approach, indicating substantially improved model fit without overfitting.

## Methods

To determine the optimal evolutionary model for HTLV-1 phylogenomics, we compared two approaches: (1) whole-genome analysis using a single evolutionary model, and (2) partition-based analysis with partition-specific models. We extracted known gene annotations for HTLV-1 (reference sequence J02029.1) and systematically compared and merged partition schemes using ModelFinder and PartitionFinder algorithms in IQ-TREE (version 2.3.5 for macOS ARM 64-bit). PartitionFinder identified three partitions optimized for model fit that align with HTLV-1 genomic organization: (1) LTR regions, (2) core genes (gag, pro, pol, env), and (3) auxiliary genes (px and HBZ). Model comparisons were based on AIC, AICc, and BIC scores. The three-partition model was selected as the best fit due to its significantly lower BIC score and superior log-likelihood compared to the whole-genome approach, indicating substantially improved model fit without overfitting.

## Methods

To determine the optimal evolutionary model for HTLV-1 phylogenomics, we compared two approaches: (1) whole-genome analysis using a single evolutionary model, and (2) partition-based analysis with partition-specific models. We extracted known gene annotations for HTLV-1 (reference sequence J02029.1) and systematically compared and merged partition schemes using ModelFinder and PartitionFinder algorithms in IQ-TREE (version 2.3.5 for macOS ARM 64-bit). PartitionFinder identified three partitions optimized for model fit that align with HTLV-1 genomic organization: (1) LTR regions, (2) core genes (gag, pro, pol, env), and (3) px and HBZ. Model comparisons were based on AIC, AICc, and BIC scores. The three-partition model was selected as the best fit due to its significantly lower BIC score and superior log-likelihood compared to the whole-genome approach, indicating substantially improved model fit without overfitting.

HTLV-1 is a RNA virus with evolutionary clock models that canonically show stability across nucleotides, most previous phylogenetic studies are based on LTR and env regions. However, Whole genome-wide phylogenomics capture comprehensive evolutionary signal and reduce biases from individual regions pylogenetics (LTR or env putative regions). In contrast, applying a single evolutionary model across the entire genome assumes uniform evolutionary processes, which can oversimplify the complex evolution of viruses and reduce phylogenetic resolution. partition-wise models are generally recommended for genome-wide viral phylogenomics to capture evolutionary rate variation and improve phylogenetic accuracy