## 1. Installing packages
```{r}
pacman::p_load(rhierbaps, devtools, ggtree, phytools, ape, here, readxl, treeio, 
               ggplot2, ggtree, tidyverse, phytools, tidytree, TDbook, reshape2, 
               ggstancea,ape, ggtreeExtra, RColorBrewer, ggnewscale, cowplot, agedenet, fastbaps, dplyr, Matrix, stringr, patchwork, data.table, ade4, irlba, fastcluster, fastbaps)
library(grDevices)
#install.packages("devtools")
#devtools::install_github("gtonkinhill/fastbaps")
#pacman::p_load(fastbaps)

#required packages
pacman::p_load(vcfR, adegenet, tidyverse, rnaturalearth, ggplot2)

#if (!requireNamespace("BiocManager", quietly = TRUE))
#install.packages("BiocManager")
BiocManager::install("LEA")

#loading packages
library(adegenet) # for dapc
library(vcfR) # for reading in genetic data
library(tidyverse) # for manipulating and plotting data
library(LEA) # For sNMF
library(rnaturalearth) #for mapping
```

## 2. Loading the data

```{r}
## loading and processing data
## read.vcfR and then vcfR2genlight
## read fasta as a Large DNAbin - extracting SNPs
htlv.fa<-fasta2genlight("/Users/denriquez/Documents/Rstats/R-main/data/0422/Beast_alignments/0430_fa_wooceania_373.fa")

## loading metadata
metadata<-as.data.frame(read.csv(file="/Users/denriquez/Documents/Rstats/R-main/0224_TreePhylo/data/metadata/finallist_381_csv_1211.csv", header=TRUE)) %>%
  filter(!Accession  %in% c("KU214243.1", "JX891478.1", "JX891479.1", "KF242505.1", "KF242506.1", "KX905202.1", "KX905203.1", "L02534.1"))

## Last version of metadata
metadata<-as.data.frame(
    read.csv(
        file="/Users/denriquez/Documents/Rstats/R-main/data/0422/0502_metadatafinal.csv", 
        header=TRUE
        )) %>%
  select(-1)

#join databases
pop <- right_join(
    data.frame(htlv.fa$ind.names),
    data.frame(metadata), 
    by=c("htlv.fa.ind.names"="Accession"
    )) 

#Join pops
htlv.fa$pop<-as.factor(pop$V2) #previous clusters
htlv.fa$pop<-as.factor(pop$Continent) #continents
levels(htlv.fa$pop)
#To test
htlv.fa$ind.names[htlv.fa$pop=="Africa"]


#### TEST
#DAPC find clusters (I have included 300 PCA and 6 clusters)
nclust<-find.clusters(htlv.fa, max.n.clust=20)

#Explore DAPC with previous data
htlv.dapc<-dapc(htlv.fa, nclust$grp, n.pca = 50, n.da = 5)

#to evaluate the number of PCAs
temp1<-optim.a.score(htlv.dapc)
scatter(htlv.dapc, posi.da="bottomright")
temp1

##############
## only admixed population
temp <- which(apply(dapcx$posterior,1, function(e) all(e<0.99)))
temp

## compoplot
compoplot(htlv.dapc, subset=temp, posi="bottomright",txt.leg=paste("Cluster", 1:6),
ncol=2, col=funky(6))
##############

##Cross-validation, NA.method="mean"
xval <- xvalDapc(htlv.dapc$tab, nclust$grp, n.pca.max = 300, training.set = 0.9, result = "groupMean", center = TRUE, scale = FALSE, n.pca = NULL, n.rep = 300, xval.plot = TRUE)
xval

scatter(pramx$DAPC, col = other(Pram)$comparePal, cex = 2, legend = TRUE,
        clabel = FALSE, posi.leg = "bottomleft", scree.pca = TRUE,
        posi.pca = "topleft", cleg = 0.75, xax = 1, yax = 2, inset.solid = 1)

##Contribution of the genome
#set.seed(4)
contrib <- loadingplot(htlv.dapc$var.contr, axis=2,
thres=.02, lab.jitter=1)
loadingplot(htlv.dapc$var.contr, axis=2, thres=.02, lab.jitter=1)
contrib

xd<-seploc(snp.htlv)
snp450<-tab(xd[["450"]])
(freq906 <- apply(snp906, 2, function(e) tapply(e, pop(H3N2), mean, na.rm = TRUE)))
# First, set the plotting parameters
# mfrow = number of columns, rows
# mar   = plot margin size
# las   = axis label style (3: always vertical)
par(mfrow = c(1, 2), mar = c(5, 4, 4, 0) + 0.1, las = 3)
par(mfrow = c(1, 2), mar = c(5, 4, 4, 0) + 0.1, las = 3)

matplot(freq906,  pch = c("c", "t"), type = "b",
        xlab = "year", ylab = "allele frequency", main = "SNP # 906",
        xaxt = "n", cex = 1.5)
axis(side = 1, at = 1:6, lab = 2001:2006)


x.pred<-predict(x.dapc)$posterior
hyb.pred<-predict(x.dapc, newdata=snp.htlv[-(1:100)])$posterior
compoplot(rbind(x.pred, hyb.pred), col.pal=virid)
res.hyb<-snapclust(snp.htlv, k=5, hybrids=TRUE, pop.ini = "kmeans")
compoplot(res.hyb, n.col=1, col.pal=hybridpal())
```

## 3. Official Run for Paper HTLV-1
```{r}
#Explore DAPC with previous data nPCA=50 and 6 clusters, nPop-1 nDA, final 100 and 5
nclust<-find.clusters(htlv.fa, max.n.clust=20)
htlv.dapc<-dapc(htlv.fa, nclust$grp, n.pca = 100, n.da = 4, scale=FALSE, var.contrib = TRUE)
scatter(htlv.dapc, posi.da="bottomleft", pch=18:23, cell=0, cstar=0, mstree=TRUE, lwd=2, lty=2)

DAPC<-as_tibble(nclust$grp, rownames="ID")
DAPC<- DAPC |>
  mutate(value=as.factor(paste("DAPC", value)))

#Convert to a tibble and join
set.seed(100588)
h_dapc_df<-as_tibble(htlv.dapc$ind.coord, rownames="individual") %>%
  mutate(group=htlv.dapc$grp) %>%
  left_join(., metadata, by=c("individual"="Accession")) %>%
  mutate(V2c = factor(case_when(
    V2  == "Africa" ~ "a-African",
    V2 %in% c("Southamerican", "Transcontinental") ~ "a-Transcontinental",
    V2 == "Japanese"~ "a-Japanese"
    ))) 
```

```{r}
#table pops vs clusters
table(htlv.fa$pop, nclust$grp)
#table comparison
#table.value(table(htlv.fa$pop, cluster.htlv$Fastbaps_OS))

######################Notes
brewer.pal(10, "Set1")
display.brewer.pal(10, "Set1")

#####################
```

```{r}
## Oficial Graph for 5 clusters
pacman::p_load(ggsci, scales)
##Colors
colors2<-ggsci::pal_nejm("default", alpha=0.9)(8)
####
"""
# K=6
h_dapc_df$group<-recode(h_dapc_df$group, "1"="TC-African", "2"="TC-Japanese A", "3"="TC-Japanese B", "5"="TC-Mixed", "4"="TC-South-America A", "6"="TC-South-America B", levels=c("TC-African", "TC-Japanese A", "TC-Japanese B", "TC-Mixed", "TC-South-America A", "TC-South-America B"))
#k=5
h_dapc_df$group<-recode(h_dapc_df$group, "3"="African", "4"="TC-Worldwide", "1"="TC-Andean-Amazon", "2"="TC-Worldwide", "5"="African")

"""
### K=4 clusters
h_dapc_df$group<-recode(h_dapc_df$group, "3"="Cosm-Japanese", "2"="TC-Worldwide", "4"="Cosm-African", "1"="TC-Andean-Amazon")

h_dapc_df$group<-factor(h_dapc_df$group, levels=c("Cosm-African", "Cosm-Japanese", "TC-Worldwide", "TC-Andean-Amazon"), ordered=TRUE)

table(htlv.fa$pop, h_dapc_df$group)

### Official plot 1 
x1<-ggplot(h_dapc_df, aes(x=LD1, y=LD2)) +
  geom_jitter(aes(fill=Continent, shape=Type), size=3, width=5, height=5, alpha=.6)+
  scale_shape_manual(name="Disease Status", values=c(21, 22, 23, 24))+
  scale_fill_manual(name="Geographic Region", values=c("#FFFF99", "#FDBF6F","#CAB2D6","#B2DF8A","#FB9A99")) +
  theme_bw(base_size=16) + 
  guides(fill=guide_legend(override.aes=list(shape=21))) +
  new_scale_color() + new_scale_fill() 
x1
x2<-x1 + new_scale_color() + new_scale_fill() +
  stat_ellipse(aes(x=LD1, y=LD2, color=group, fill=group), alpha=0.1, size=1, level = 10, geom="polygon", type="euclid")+
  scale_color_manual(name="Cluster", values=c("#FFDC91E5","#E18727E5","#91D1C2B2", "#E64B35B2"), guide="legend") +
  scale_fill_manual(name="Cluster", values=c("#FFDC91E5","#E18727E5","#91D1C2B2", "#E64B35B2") )+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(),
plot.margin=unit(c(5,5,5,5),"mm"),
legend.title = element_text(size=12, face="bold"),
legend.position="bottom",
legend.direction="vertical",
legend.justification = "top",
legend.text=element_text(size=12),
legend.margin = margin(0.2, unit="cm"),
legend.spacing.x = unit(0.7, 'cm'),
legend.key.height=unit(0.5,"cm"),
legend.key.width=unit(0.5,"cm"))

x2
#save this plot
ggsave("2510_DAPC_4clusters.tiff", plot = last_plot(),  path=here("output/"), scale=1, dpi=600, limitsize=FALSE)


# dapc plot v2
y1<-ggplot(h_dapc_df, aes(x=LD1, y=LD2)) +
  geom_jitter(aes(fill=V2c, shape=Type), size=3, width=5, height=5, alpha=.6) +
  scale_shape_manual(name="Disease Status", values=c(21, 22, 23, 24))+
  scale_fill_manual(name="Genotype", values=c("#FFFF33","#FF7F00","#E41A1C")) +
  theme_bw(base_size=16) + 
  guides(fill=guide_legend(override.aes=list(shape=21))) +
  new_scale_color() + new_scale_fill() 
y1
y2<-y1 + new_scale_color() + new_scale_fill() +
  stat_ellipse(aes(x=LD1, y=LD2, color=group, fill=group), alpha=0.1, size=1, level = 10, geom="polygon", type="euclid")+
  scale_color_manual(name="Cluster", values=c("#FFDC91E5","#E18727E5","#91D1C2B2", "#E64B35B2"), guide="legend") +
  scale_fill_manual(name="Cluster", values=c("#FFDC91E5","#E18727E5","#91D1C2B2", "#E64B35B2"))+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(),
plot.margin=unit(c(5,5,5,5),"mm"),
legend.title = element_text(size=12, face="bold"),
legend.position="bottom",
legend.direction="vertical",
legend.justification = "top",
legend.text=element_text(size=12),
legend.margin = margin(0.2, unit="cm"),
legend.spacing.x = unit(0.7, 'cm'),
legend.key.height=unit(0.5,"cm"),
legend.key.width=unit(0.5,"cm"))

y2
#save this plot
ggsave("2510_DAPC_genotypes.tiff", plot = last_plot(),  path=here("output"), scale=1, dpi=600, limitsize=FALSE)
```

## 4. Map Peru
```{r}
## Peruvian MAP
pacman::p_load(readxl, mapsPERU)
pacman::p_load(dplyr, remotes, sf, dplyr, ggplot2, janitor, scatterpie)

dfmap<-map_DEP %>%
  mutate(DEPARTAMENTO=make_clean_names(DEPARTAMENTO)) %>%
  mutate(DEPARTAMENTO=toupper(DEPARTAMENTO)) 

tab1<-read_csv("/Users/denriquez/Documents/Rstats/R-main/data/0422/00504_table1_db")

tabx <- tab1 %>%
  right_join(.,h_dapc_df, by=c("Accession"="individual")) %>%
  filter(Country %in% c("Peru", "Brazil", "Chile")) %>%
  mutate(Residence=factor(case_when(Country == "Brazil" ~ "Brazil", Country == "Chile" ~"Chile", Country=="Peru" ~ Residence))) %>%
  mutate(Residence=make_clean_names(Residence, allow_dupes = TRUE)) %>%
  mutate(Residence=toupper(Residence)) %>%
  select(Accession,Residence,group) %>%
  group_by(Residence) %>%
  count(Residence, group) %>%
  mutate(sum_counts=sum(n)) %>%
  spread(group, n, fill=0) %>%
  full_join(.,dfmap, by=c("Residence"="DEPARTAMENTO")) 
 
tabx$coords_x[tabx$Residence=="BRAZIL"]<--70
tabx$coords_y[tabx$Residence=="BRAZIL"]<--7
tabx$coords_x[tabx$Residence=="CHILE"]<--70
tabx$coords_y[tabx$Residence=="CHILE"]<--20

tabx$sum_counts2<-cut(tabx$sum_counts, right=F, breaks=c(1,5,10, 20, 200), labels=c("1-5", "5-10", "10-20", ">20"))
colores <- c('#feebe0','#fbb4b9','#f768a1','#ae017e')

colnames(tabx)

p1p<-ggplot(tabx, aes(geometry=geometry))+
  geom_sf(data=tabx, aes(fill=sum_counts2)) + scale_fill_manual(name="HTLV-1 Cases", values=colores, na.value="lightgrey") + new_scale_fill()
p1p
p2p<-p1p+ geom_scatterpie(aes(x=coords_x, y=coords_y), data=tabx, cols=c("Cosm-African","Cosm-Japanese","TC-Worldwide","TC-Andean-Amazon"), alpha=1, pie_scale=2)+ 
  labs(fill="Cluster") +
  scale_fill_manual(name="Cluster",values=c("#FFDC91E5","#E18727E5", "#91D1C2B2","#E64B35B2")) +
  new_scale_fill()+
  geom_text(data=tabx[tabx$Residence =="BRAZIL",], aes(x=coords_x, y=coords_y-1, label=Residence))+
  geom_text(data=tabx[tabx$Residence =="CHILE",], aes(x=coords_x, y=coords_y-1, label=Residence))+
                      #ggtitle("Geographic Cluster Distribution of HTLV-1 in Peru, Chile and Brazil")+ 
  theme(
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.title = element_text(size=14),
    legend.text=element_text(size=12),
  ) 
p2p
ggsave("241022_PeruHTLV.tiff", plot = last_plot(),  path=("./output/"), scale=1, dpi=600, limitsize=TRUE)
```

## 5. Map distances

```{r}
#loading packages
pacman::p_load(vegan, ape, tidyverse)

#function 
f_genetic_distances_groups<-function(
    fasta_path, 
    metadata_path, 
    accession_name, 
    group_name, 
    output_file){
  #Import Fasta
  fas<-ape::read.FASTA(fasta_path, type="DNA")
  #Import Metadata
  metd<-read.csv(metadata_path, sep=',')
  #distancematrix
  matrix_fa<-ape::dist.dna(fas, model="K80", pairwise.deletion = TRUE)
  #groups
  ids<-labels(matrix_fa)
  gr<-metd[match(ids, as.character(metd[,accession_name])), group_name]
  #get mean distance matrix within and between groups
  matrix_dist<-vegan::meandist(matrix_fa, gr)
  #visualize
  print(matrix_dist)
  #save it!
  write.table(matrix_dist,
            paste0(output_file,noquote(group_name), ".tsv"), sep="\t",quote=F, col.names=TRUE, row.names=T)
}

#distance matrix excluding outliers
matrix = f_genetic_distances_groups(fasta_path="/Users/denriquez/Documents/Rstats/R-main/data/0422/Beast_alignments/0430_fa_wooceania_373.fa", 
    metadata_path="/Users/denriquez/Documents/Rstats/R-main/data/0422/0502_metadatafinal.csv", 
    accession_name="Accession", 
    group_name="V2", 
    output_file="/Users/denriquez/Documents/Rstats/R-main/data/0422/2510_redoing")

#load matrix table

htlvmatrix<-read.csv2("/Users/denriquez/Documents/Rstats/R-main/data/0422/2510_redoing.csvV2.tsv",header = T,sep = "\t")

htlvmatrix = htlvmatrix|>
as.matrix() %>%
  as_tibble(rownames = "Cluster") %>%
  pivot_longer(-Cluster, names_to="B", values_to="Distances") %>%
  mutate(Distances=as.numeric(Distances)) %>%
  mutate(Clusterx=recode_factor(Cluster, "Africa"="Cosm-African", "Southamerican"="TC Andean-Amazonian", "Transcontinental"="TC Worldwide", "Japanese"="Cosm-Japanese")) %>%
  mutate(Bx=recode_factor(B, "Africa"="Cosm-African", "Southamerican"="TC Andean-Amazonian", "Transcontinental"="TC Worldwide", "Japanese"="Cosm-Japanese")) %>%
  mutate(Bx=fct_relevel(Bx, "TC Andean-Amazonian", "TC Worldwide", "Cosm-Japanese", "Cosm-African")) %>%
  mutate(Clusterx=fct_relevel(Clusterx, "TC Andean-Amazonian", "TC Worldwide", "Cosm-Japanese", "Cosm-African")) %>% mutate(Distances=if_else(as.numeric(Clusterx)>=as.numeric(Bx),Distances,NA)) %>%
  filter(!is.na(Distances))
    
#Half heatmap plot
htlvmatrix %>%       
  ggplot(aes(x=Clusterx, y=Bx, fill=Distances))+
  geom_tile()+
  scale_fill_viridis_c(direction=-1) + 
  theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.text.y = element_text(size = 12, face="bold"),
  axis.text.x = element_text(size = 12, angle=25, vjust=1, hjust=1, face="bold"),
  axis.title.y = element_blank(),
  legend.title = element_text(size = 16, face="bold"),
  legend.text = element_text(size = 16))

#save this plot
ggsave("2410_heatmapdistances.tiff", plot = last_plot(),  path=("output/"), scale=1, dpi=600, limitsize=TRUE)
```