## 1. Loading packages
```{r}
pacman::p_load(here, readxl, treeio, ggplot2, ggtree, tidyverse, phytools, tidytree, TDbook, reshape2,ape, ggtreeExtra, RColorBrewer, ggnewscale, cowplot)
#BiocManager::install("ggtreeExtra")
#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

nodeid.tbl_tree <- utils::getFromNamespace("nodeid.tbl_tree", "tidytree")
rootnode.tbl_tree <- utils::getFromNamespace("rootnode.tbl_tree", "tidytree")
offspring.tbl_tree <- utils::getFromNamespace("offspring.tbl_tree", "tidytree")
offspring.tbl_tree_item <- utils::getFromNamespace(".offspring.tbl_tree_item", "tidytree")
child.tbl_tree <- utils::getFromNamespace("child.tbl_tree", "tidytree")
parent.tbl_tree <- utils::getFromNamespace("parent.tbl_tree", "tidytree")
```

## 2. Loading data

```{r}
#Mac
metadata<-as.data.frame(read.csv(file="/Users/denriquez/Documents/Rstats/R-main/0224_TreePhylo/data/metadata/finallist_381_csv_1211.csv", header=TRUE))  %>%
  filter(Accession!= "KU214243.1")

```


```{r}
#tree import
#arbol<-read.iqtree("C:/Rdev/R2401/0224_TreePhylo/data/processed_data/0409_finaloptMLtree.raxml.support")

##MAC
tree<-read.newick("/Users/denriquez/Documents/Rstats/R-main/data/0422/0424_tbe.raxml.support")
#tree_data<-here("data","raw_data","evaT1.raxml.bestTree")
#tree_raw<-read.newick(tree_data)
#tree$tip.label<-gsub('\\.','_',tree$tip.label)
#write.tree(tree, file="C:/Rdev/R2401/data/0422/0509_treeforhyphy")#just to check structure

##to check if all are included in tiplabels before joining.
#tree$tip.label
#metadata[tree$tip.label%in% metadata$Accession,]

#review nodes
ggtree(tree, layout="rectangular", open.angle=10, color="darkgray", size=0.7)+geom_text2(aes(subset=!isTip,label=node), hjust=-.3, size=1)+geom_tiplab(size=1)
ggsave("t0_raw.pdf", plot = last_plot(),  path=here("output/0422tree"), scale=1, dpi=300, limitsize=FALSE)

#reroot
t_rooted<-reroot(tree, 712) %>%
  as_tibble() %>%
  left_join(., metadata, by = c("label"="Accession")) %>%
  mutate(label=gsub("\\.\\d$",'',label)) %>%
    as.treedata()
tree2<-reroot(tree, 712) 
#reroot v2
#root.phylo(tree_raw, node=628, resolve.root = TRUE, is.rooted=FALSE) %>% ggtree()
#ggtree(t_rooted)

#tibble of rerooted tree
tree_tib<-as_tibble(tree2)
#fusion with metadata
tree3<-left_join(tree_tib,metadata, by = c("label"="Accession"))
#change names
tree3$label<-gsub("\\.\\d$",'',tree3$label)
#tree_tib2$label<-gsub("\\_S\\d+$",'',tree_tib2$label)
#back to tree from tibble
tree3raw<-as.treedata(tree3)

#just to watch
#ggtree(tree_raw2)

#review nodes
ggtree(t_rooted, layout="rectangular", open.angle=10, color="darkgray", size=0.7)+geom_text2(aes(subset=!isTip,label=node), hjust=-.3, size=1)+geom_tiplab(size=1)
ggsave("t1.pdf", plot = last_plot(),  path=here("output/0422tree"), scale=1, dpi=300, limitsize=FALSE)
```

```{r}

pacman::p_load(checkpoint)
checkpoint("2025-10-01")  # Date when your desired version was current
pacman::p_load(ggplot2, ggtree)
coltext=c("#4daf4a","#984ea3", "#a6761d", "#E41a1c")

#main tree
p0<-ggtree::ggtree(t_rooted, layout="circular", ize = 0.5, branch.length = "none", color = "darkgrey") +
  geom_tiplab(geom="text",
              aes(subset=grepl("Japan|Chile|Brazil|Peru", Country),
                  color=factor(Country)), size=1.2, offset=8.5) +
  scale_colour_manual(guide="legend", name="Countries", values=c("#4daf4a","#a6761d","#E41a1c","#984ea3"), labels=c("Brazil", "Japan","Peru","Chile"), na.value="black") +
  geom_tiplab2(aes(subset=(!grepl("Japan|Chile|Brazil|Peru", Country))), color="black",size=1.2, offset=8.5)

p0<-p0+ new_scale_color()+ new_scale_fill()
p0


p0 <- ggtree(t_rooted, layout = "circular", size = 0.5, branch.length = "none", color = "darkgrey")  +
  geom_tiplab(aes(label = label,
                  subset = grepl("Japan|Chile|Brazil|Peru", Country),
                  color = Country),
              size = 1.2, offset = 8.5, geom = "text") +
  scale_color_manual(name = "Countries",
                     values = c("Brazil" = "#4daf4a",
                                "Japan"  = "#984ea3",
                                "Peru"   = "#E41a1c",
                                "Chile"  = "#a6761d"),
                     na.value = "black",
                     breaks = c("Brazil","Japan","Peru","Chile")) +
  geom_tiplab2(aes(subset = !grepl("Japan|Chile|Brazil|Peru", Country)),
               color = "black", size = 1.2, offset = 8.5) +
  new_scale_color() + new_scale_fill()


pacman::p_load(magick)
img <- image_read("2510_tree/treeFinal1_0505_slides.png")
image_write(img, path = "2510_output.tiff", format = "tiff",
            compression = "lzw", quality = 100, density = 600)
```